name: TwinCAT Style Check

on:
  push:
  pull_request:

jobs:
  style:
    runs-on: ubuntu-20.04

    defaults:
      run:
        # The following allows for each run step to utilize ~/.bash_profile
        # for setting up the per-step initial state.
        # --login: a login shell. Source ~/.bash_profile
        # -e: exit on first error
        # -o pipefail: piped processes are important; fail if they fail
        shell: bash --login -eo pipefail {0}

    steps:
    - uses: actions/checkout@v3

    - name: Find all source code files
      run: |
        TWINCAT_PROJECT_ROOT=.
        TWINCAT_STYLE_EXCLUDE=

        cat > "$HOME/files.sh" <<EOF
          all_files=$(find $TWINCAT_PROJECT_ROOT -regextype posix-extended -regex '.*\.(TcPOU|TcDUT|TcGVL)$')
          if [ -z "${TWINCAT_STYLE_EXCLUDE}" ]; then
            echo "${all_files}"
          else
            echo "${all_files}" | egrep -v "${TWINCAT_STYLE_EXCLUDE}"
          fi
        EOF

    - name: List project files
      run: |
        echo "Project files are as follows:"
        echo "-----------------------------"
        bash "$HOME/files.sh"
        echo "-----------------------------"

    - name: Setting up summary
      run: |
        (
          echo ""
          echo "### Style check"
          echo ""
        ) >> "$GITHUB_STEP_SUMMARY"

    - name: Checking for leading tabs
      run: |
        tab_lines=$(bash "$HOME/files.sh" | xargs grep -En $'^\s*\t')
        if [ -n "${tab_lines}" ]; then
          tab_count=$(echo "${tab_lines}" | wc -l)
          echo "Found ${tab_count} lines with leading tabs" | tee -a "$GITHUB_STEP_SUMMARY"
          echo "${tab_lines}"
          exit 1
        fi

        echo "Success: Found no lines with tabs."

    - name: Checking for trailing whitespace
      if: ${{ always() }}
      run: |
        whitespace_lines=$(bash "$HOME/files.sh" | xargs grep -En $' +$| +\r$')
        if [ -n "${whitespace_lines}" ]; then
          whitespace_count=$(echo "${whitespace_lines}" | wc -l)
          echo "Found ${whitespace_count} lines with trailing whitespace" | tee -a "$GITHUB_STEP_SUMMARY"
          echo "${whitespace_lines}"
          exit 1
        fi

        echo "Success: Found no lines with trailing whitespace"

    - name: Checking for TwinCAT misconfiguration (Line IDs)
      if: ${{ always() }}
      run: |
        lineid_lines=$(bash "$HOME/files.sh" | xargs grep -n 'LineId')
        if [ -n "${lineid_lines}" ]; then
          lineid_count=$(echo "${lineid_lines}" | wc -l)
          echo "Found ${lineid_count} lines with same-file debug line ids (fix your twincat config)" | tee -a "$GITHUB_STEP_SUMMARY"
          echo "${lineid_lines}"
          exit 1
        fi

        echo "Success: Found no debug line ids"
