name: TwinCAT Style Check

on:
  push:
  pull_request:

jobs:
  style:
    runs-on: ubuntu-20.04

    defaults:
      run:
        # The following allows for each run step to utilize ~/.bash_profile
        # for setting up the per-step initial state.
        # --login: a login shell. Source ~/.bash_profile
        # -o pipefail: piped processes are important; fail if they fail
        shell: bash --login -o pipefail {0}

    steps:
    - uses: actions/checkout@v3

    - name: Find all source code files
      run: |
        TWINCAT_PROJECT_ROOT=.
        TWINCAT_STYLE_EXCLUDE=_unset_
        if [ -z "${TWINCAT_STYLE_EXCLUDE}" ]; then
          TWINCAT_STYLE_EXCLUDE=__unset__
        fi

        cat > "$HOME/files.sh" <<EOF
          find "$TWINCAT_PROJECT_ROOT" -print0 -type f \
            | egrep --null-data --null --ignore-case -e $"\.TcPOU$" -e $"\.TcDUT$" -e $"\.TcGVL$" \
            | egrep --null-data --null --invert-match -e "${TWINCAT_STYLE_EXCLUDE}"
        EOF

    - name: List project files
      run: |
        cat $HOME/files.sh
        echo "Project files are as follows:"
        echo "-----------------------------"
        bash "$HOME/files.sh" | xargs -0 -n1 echo
        echo "-----------------------------"

    - name: Setting up summary
      run: |
        (
          echo ""
          echo "### Style check"
          echo ""
        ) >> "$GITHUB_STEP_SUMMARY"

    - name: Checking for leading tabs
      run: |
        which egrep
        tab_lines=$(bash "$HOME/files.sh" | xargs -0 -n1 egrep --line-number $'^\s*\t')
        if [ -n "${tab_lines}" ]; then
          tab_count=$(echo "${tab_lines}" | wc -l)
          echo "Found ${tab_count} lines with leading tabs" | tee -a "$GITHUB_STEP_SUMMARY"
          echo "${tab_lines}"
          exit 1
        fi

        echo "Success: Found no lines with tabs."

    - name: Checking for trailing whitespace
      # Run all checks regardless of the *previous* one passing or failing.
      # Do not use 'always()' here in case of cancelation or prior essential
      # steps failing.
      if: ${{ success() || failure() }}
      run: |
        whitespace_lines=$(bash "$HOME/files.sh" | xargs -0 -n1 egrep --line-number -e $'\s+$')
        if [ -n "${whitespace_lines}" ]; then
          whitespace_count=$(echo "${whitespace_lines}" | wc -l)
          echo "Found ${whitespace_count} lines with trailing whitespace" | tee -a "$GITHUB_STEP_SUMMARY"
          echo "${whitespace_lines}"
          exit 1
        fi

        echo "Success: Found no lines with trailing whitespace"

    - name: Checking for TwinCAT misconfiguration (Line IDs)
      if: ${{ success() || failure() }}
      run: |
        lineid_lines=$(bash "$HOME/files.sh" | xargs -0 -n1 egrep --line-number -e $'LineId')
        if [ -n "${lineid_lines}" ]; then
          lineid_count=$(echo "${lineid_lines}" | wc -l)
          echo "Found ${lineid_count} lines with same-file debug line ids (fix your twincat config)" | tee -a "$GITHUB_STEP_SUMMARY"
          echo "${lineid_lines}"
          exit 1
        fi

        echo "Success: Found no debug line ids"
